- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False
  
  tasks:
    - include: tasks/initial-setup.yml
    # - include: tasks/users.yml
    # - include: tasks/cron.yml
    - include: tasks/enable-bash.yml
    - include: tasks/packages.yml
    # - include: tasks/autofs.yml
