- name: make home for bluepixels
  command: "{{ item }}"
  with_items:
  - mkdir -p /opt/home/bluepixels
  - chown -R bluepixels:bluepixels /opt/home/bluepixels
  - usermod -d /opt/home/bluepixels bluepixels
