- name: make home for bluepixels
  file:
    path: /opt/home/bluepixels
    state: directory
    owner: bluepixels
    group: bluepixels
    mode: 0755

- name: change home of bluepixels
  command: usermod -d /opt/home/bluepixels bluepixels
