- name: enable bash
  command: "sudo {{ item }}"
  with_items:
  - apt install debconf-utils -y -f
  - echo "dash dash/sh boolean false" | debconf-set-selections
  - DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
