- name: install openssh
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - openssh-server
      - openssh-client

- name: copy sshd_config
  copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644

- name: restart sshd
  command: systemctl restart sshd
