- name: set python path
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    owner: root
    group: root
    state: link

- name: create crap folders
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items:
    - /crap/LOCAL.crap
    - /crap/versionCache
    - /crap/mercurial

- name: make crap symlink
  file:
    src: /blueprod/CRAP/crap
    dest: /crap/crap.server
    force: yes
    owner: root
    group: root
    state: link

- name: make symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    state: link
  with_items:
    - { src: '/blueprod/STOR1/proj', dest: '/proj' }
    - { src: '/blueprod/STOR1/projdump', dest: '/projdump' }
    - { src: '/blueprod/STOR1/library', dest: '/library' }
