#!/bin/bash
export LC_ALL="en_US.UTF-8"

if [[ $USER = "bluepixels" ]]; then
  echo "Not available to bluepixels"
else
  /proj/standard/share/blender-2.80-rc/blender --python /projdump/pythonTestWindoze.DONOTDELETE/rbhus/etc/startupScripts/blend/beforeFile.py "$@" --python /projdump/pythonTestWindoze.DONOTDELETE/rbhus/etc/startupScripts/blend/afterFile.py
fi
