#!/bin/bash
export LC_ALL="en_US.UTF-8"

if [[ $USER = "bluepixels" ]]; then
  echo "Not available to bluepixels"
else
  /proj/standard/share/blender-2.82a-linux64/blender --python /blueprod/CRAP/crap/softwares/blender/addons/startupScripts/beforeFile_2_8.py "$@" --python /blueprod/CRAP/crap/softwares/blender/addons/startupScripts/afterFile_2_8.py
fi
