#!/bin/bash
export LC_ALL="en_US.UTF-8"

if [[ $USER = "bluepixels" ]]; then
  echo "Not available to bluepixels"
else
  /proj/standard/share/blender-3.3-lts/blender --python /proj/standard/share/startupScripts/beforeFile_3_3.py "$@" --python /proj/standard/share/startupScripts/afterFile_3_3.py
fi
